---
controller:
  replicas: 1
  strategy: RollingUpdate
  type: deployment

image:
  repository: nginx
  tag: 1.14.2
#  repository: 186312734932.dkr.ecr.us-west-2.amazonaws.com/demo-app
#  pullPolicy: Always
#  tag: v0.1.0

podLabels:
  app: "demo-app"

imagePullSecrets:
  - name: regcred

resources:
  requests:
    memory: "50Mi"
    cpu: "50m"
  limits:
    memory: "200Mi"
    cpu: "200m"

service:
  main:
    enabled: false
    ports:
      http:
        enabled: true
        port: 80

probes:
  liveness:
    enabled: true
    httpGet:
      path: /
      port: 80
  readiness:
    enabled: true
    httpGet:
      path: /
      port: 80
  startup:
    enabled: true
    httpGet:
      path: /
      port: 80

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: network
              operator: In
              values:
                - private

persistence:
  htlm:
    enabled: true
    type: configMap
    name: demo-app-html
    mountPath: /usr/share/nginx/html/index.html
    subPath: index.html

configMaps:
  html:
    enabled: true
    data:
      index.html: |
        <body style="text-align: center;">
        <h1 > Welcome Scrollers ! </h1>
        <p style="font-size: 22px;"> This is a simple demo app using argocd and helm charts :) </p>
        <img src="https://upload.wikimedia.org/wikipedia/commons/3/33/Cartoon_space_rocket.png"  width="300" height="300">
        </body>

ingress:
  main:
    enabled: false
    primary: true
    annotations:
      nginx.ingress.kubernetes.io/limit-rps: "1"
    labels: {}
    ingressClassName: "nginx"
    hosts:
      - host: kargo-demo-mainnet.devnet.scroll.tech
        paths:
          - path: /
            pathType: Prefix
    tls: []
