---
apiVersion: v2
description: Demo application to demonstrate argocd deployment
name: demo-app
version: 0.1.0
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-sre
    email: sebastien@scroll.io
dependencies:
  - name: common
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 1.5.1
  - name: cilium-lib
    repository: "oci://ghcr.io/scroll-tech/helm"
    version: 0.0.1
  - name: external-secrets-lib
    repository: "oci://ghcr.io/scroll-tech/helm"
    version: 0.0.2
